---
- hosts: aruba
  collections:
  - arubanetworks.aos_switch
  gather_facts: false
  vars:
    date: "{{ lookup('pipe', 'date +%Y_%m_%d-%H_%M') }}"
  tasks:
  - name: backup up running-config
    arubaoss_config:
      backup: yes
      backup_options:
        dir_path: /var/lib/awx/projects
        filename: aruba_config_"{{ date }}".cfg
