---
- hosts: aruba
  collections:
  - arubanetworks.aos_switch
  vars:
    date: "{{ lookup('pipe', 'date +%Y_%m_%d-%H_%M') }}"
  tasks:
  - name: backup up running-config
    arubaoss_config:
      backup: yes
      backup_options:
        filename:  aruba_config_"{{ date }}".cfg
        dir_path: /home/ftpuser/ftp/files
