---
- name: Config von Aruba_switch zurücksichern
  hosts: aruba
  collections:
  - arubanetworks.aos_switch
  tasks:
  - name: debug
    debug:
    {{ results }}
  - name: Backup config
    arubaoss_config_bkup:
      file_name: test
