---
- name: Backup current config
  collection: fortinet.fortios.fortios_system_config_backup_restore
  hosts: fortigate
  connection: httpapi
  gather_facts: no
  tasks:
    - name: backup
      fortios_config:
        backup: yes
