---
- name: Backup current config
  hosts: fortigate
  tasks:
    - name: backup
      fortios_config:
        username: admin
        password: Start-123
        backup: yes
        backup_path: /etc/ansible/
