---
- name: Backup current config
  hosts: fortigate
  connection: httpapi
  ansible_network_os: fortios
  gather_facts: no
  tasks:
    - name: backup
      fortios_config:
        backup: yes
        backup_path: /etc/ansible/
