---
- name: Backup current config
  hosts: 192.168.0.99
  gather_facts:  no
  tasks:
    - name: backup
      fortios_config:
        host: 192.168.0.99
        username: admin
        password: Start-123
        backup: yes
        backup_path: /etc/ansible/
