---
#installs vlc
- name: Install vlc on windows hosts
  hosts: win
  strategy: free
  tasks:
    - name: Install application and override expected return codes
      win_package:
        path: https://ftp.fau.de/videolan/vlc/3.0.16/win32/vlc-3.0.16-win32.exe
        state: present
