---
- hosts: ubuntu_test
  become: true
  tasks:
    - name: Install required packages
      apt: 
        name:  
          - php-cli
          - nginx
          - mysql-server
        update_cache: yes
