---
- hosts: ubuntu_test
  become: yes
  tasks:
    - name: Start Services
      service:
        name: {{ item }}
        state: started
        enabled: yes
      with_item:
        - nginx
        - php-cli
        - mysql-server
