---

- name: rename multiple hosts and reboot if required

  hosts: win

  vars:

    hostinfo:

    - host: 192.168.0.98

      name: windows1123123

    - host: 192.168.0.128

      name: windows2232

  tasks:

  - name: Change the hostname to sample-hostname

    ansible.windows.win_hostname:

      name: "{{ item.name }}"

    when: ansible_host  == item.host

    with_items: "{{ hostinfo }}"

    register: restart



  - debug:

      var: restart


