---
- name: rename multiple hosts and reboot if required
  hosts: win
- tasks:
  - name: Change the hostname to sample-hostname
    hosts: win  
    ansible.windows.win_hostname:
      name: windows[1:2]
    register: res

  - name: Reboot
    hosts: win
    ansible.windows.win_reboot:
    when: res.reboot_required
