---
- name: rename multiple hosts and reboot if required
  hosts: win
  gather_facts: false
  vars:
    hostinfo:
      host1:
        name: WindowsDemo1
        ip: 192.168.0.98
      host2:
        name: WindowsDemo2
        ip: 192.168.0.128

  tasks:
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: "{{ item.value.name }}"
    loop: "{{ lookup('dict', hostinfo) }}"
    when: ansible_host  == item.value.ip
    register: res

  - name: debug
    debug:
      msg: "{{ res | community.general.json_query('results[*].reboot_required') }}"

  - name: reboot if required
    ansible.windows.win_reboot:
    when: res | community.general.json_query('results[*].reboot_required') == 'true'
