---
- name: Benenne mehrere Hosts um und starte neu, falls erforderlich
  hosts: win

  tasks:
  - name: Ändere den Computernamen entsprechend der Liste
    ansible.windows.win_hostname:
      name: "{{ item.value.name }}"
    # Schleife durch dictionary 'hostinfo'
    loop: "{{ lookup('dict', hostinfo) }}"
    when: ansible_host  == item.value.ip
    register: res
    # hinterlegt "reboot_required" im Register

  - name: Neustart, falls der Name geändert wurde
    ansible.windows.win_reboot:
    when: res | json_query('results[*].reboot_required') is any == true
    # Schleife durch das Register prüft, ob Variable 'reboot_required' den Wert 'true' hat0
