---
- name: rename multiple hosts and reboot if required
  hosts: win
  tasks:
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: "{{ item.name }}"
      when: "{{ ansible_hostname == item.host }}"
      with-items:
        hostinfo:
        - host: 192.168.0.98
          name: windows1
        - host: 192.168.0.128
          name: windows2   
    register: res
    
  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
