---
- name: Benenne mehrere Hosts um und starte neu, falls erforderlich
  hosts: win
  vars:
    hostinfo:
      host1:
        name: SAC1
        ip: 192.168.0.98
      host2:
        name: SAC2
        ip: 192.168.0.128

  tasks:
  - name: Ändere den Computernamen entsprechend der Liste
    ansible.windows.win_hostname:
      name: "{{ item.value.name }}"
    # Schleife durch dictionary 'hostinfo'
    loop: "{{ lookup('dict', hostinfo) }}"
    when: ansible_host  == item.value.ip
    register: res
    # hinterlegt "reboot_required" im Register

- name: say debug
    debug:
      msg: "{{ res | json_query('results[*].reboot_required') is any }}"
    # gibt den Wert für 'reboot required' des entsprechendes Hosts auf der Konsole aus ('true' oder 'false')

 - name: Neustart, falls der Name geändert wurde
   ansible.windows.win_reboot:
   when: res | json_query('results[*].reboot_required') is any == true
   # Schleife durch das Register prüft, ob Variable 'reboot_required' den Wert 'true' hat0
