---
- name: rename multiple hosts and reboot if required
  hosts: win
  vars_files:
   /home/awx/vars/host.yml
  tasks:
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: "{{item.name}}"
      when: "{{ansible_hostname == item.host}}"
      with_items: "{{hostinfo}}"
    register: res
    
  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
