---
- name: rename multiple hosts and reboot if required
  hosts: win
  tasks:
  - name: Change the hostname to sample-hostname
    host: win[0]
    ansible.windows.win_hostname:
      name: windows1
    register: res
    
  - name: Change the hostname to sample-hostname 2
    host: win[1]
    ansible.windows.win_hostname:
      name: windows2
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
